# This notebook looks at basic numerical operations using numpy


## __For numerical calculations python has  numpy package__

In [88]:
import numpy as np

## Matrix dimenstions and manipulating them
Let's make a one dimensional array and manipulate it

In [89]:
v=np.array([1,2,3,4,5,6])
print(v)
print(v.shape)
print(v+v)
print(10*v+3)
print(2**v)

[1 2 3 4 5 6]
(6,)
[ 2  4  6  8 10 12]
[13 23 33 43 53 63]
[ 2  4  8 16 32 64]


The vector above looked like a row vector so transposing it should give a column vector.

In [90]:
print(np.transpose(v))
print(np.transpose(v).shape)

[1 2 3 4 5 6]
(6,)


In [91]:
v1=np.array([1,2,3,4,5,6])
v2=v1.reshape((1,6)) # reshape is quite useful 
print('v1:{}'.format(v1))
print('v2:{}'.format(v2))
#v1 and v2 looks similar but one of them is one dimensional and the other one is not
print('v1 shape:{}'.format( v1.shape  ))
print('v2 shape:{}'.format( v2.shape  ))
#
print("Doing transpose:")
print('v1:{}'.format( np.transpose(v1)  ))
print('v1:{}'.format( np.transpose(v2) ))
#"Transposing a 1-D array returns an unchanged view of the original array." : Numpy documentation

v1:[1 2 3 4 5 6]
v2:[[1 2 3 4 5 6]]
v1 shape:(6,)
v2 shape:(1, 6)
Doing transpose:
v1:[1 2 3 4 5 6]
v1:[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


## Basic matrics

In [92]:
print('np.ones(3) :{}'.format( np.ones(3)  ))
print('np.zeros(3) :{}'.format( np.zeros(3)  ))
print('np.linspace(0,10,11) :{}'.format( np.linspace(0,10,11)  ))
print('np.logspace(0,5,6) :{}'.format( np.logspace(0,5,6)  ))
print('random samples from a uniform distribution over [0, 1): np.random.rand(3) :{}'.format( np.random.rand(3)  ))
print('random samples from a Gaussian distribution of mean 0 and variance 1: np.random.randn(3) :{}'.format( np.random.randn(3)  ))
print('random samples from a Gaussian distribution of mean 10 and Standard deviation 2: np.random.normal(10,2,(3,4)) :\n{}'.format( np.random.normal(10,2,(3,4))  ))
#print('np. :{}'.format( np.  ))
#print('np. :{}'.format( np.  ))


np.ones(3) :[1. 1. 1.]
np.zeros(3) :[0. 0. 0.]
np.linspace(0,10,11) :[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
np.logspace(0,5,6) :[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]
random samples from a uniform distribution over [0, 1): np.random.rand(3) :[0.43120887 0.89626571 0.32718574]
random samples from a Gaussian distribution of mean 0 and variance 1: np.random.randn(3) :[ 1.0429677   0.19167475 -2.20982663]
random samples from a Gaussian distribution of mean 10 and Standard deviation 2: np.random.normal(10,2,(3,4)) :
[[ 9.90582678 12.45080418  8.3359666  10.07536508]
 [11.556831    9.46861835  8.25027777  8.55449327]
 [12.87671382 11.22874336 12.39207338 10.24879257]]


There are many distributions available:
https://docs.scipy.org/doc/numpy-1.14.1/reference/routines.random.html

## Elementwise operations:

In [93]:
#Adding elements
v1=np.array([1,2,3,4]).reshape(2,2)
v2=np.array([1,2,10,10]).reshape(2,2)
print( "v1:\n {}".format( v1 ) )
print( "v2:\n {}".format( v2 ) )
print( "Elementwise addition v1+v2:\n {}".format(v1+v2  ) )

print( "Elementwise multiplication np.multiply(v1,v2):\n {}".format( np.multiply(v1,v2) ) )
print( "Elementwise multiplication np.multiply(v2,v1):\n {}".format( np.multiply(v2,v1) ) )

print( "Elementwise multiplication v1*v2 (Short hand notation) :\n {}".format(v1*v2  ) )

v1:
 [[1 2]
 [3 4]]
v2:
 [[ 1  2]
 [10 10]]
Elementwise addition v1+v2:
 [[ 2  4]
 [13 14]]
Elementwise multiplication np.multiply(v1,v2):
 [[ 1  4]
 [30 40]]
Elementwise multiplication np.multiply(v2,v1):
 [[ 1  4]
 [30 40]]
Elementwise multiplication v1*v2 (Short hand notation) :
 [[ 1  4]
 [30 40]]


## Matrix operation:

In [94]:
v1=np.array([1,2,3,4]).reshape(2,2)
v2=np.array([1,2,10,10]).reshape(2,2)
print( "v1:\n {}".format( v1 ) )
print( "v2:\n {}".format( v2 ) )

print( "Matrix multiplication np.dot(v1,v2):\n {}".format( np.dot(v1,v2) ) )

print( "Matrix multiplication np.dot(v2,v1):\n {}".format( np.dot(v2,v1) ) )

print( "Matrix multiplication v1@v2:  short hand notation @:\n {}".format( v1@v2) ) 


v1:
 [[1 2]
 [3 4]]
v2:
 [[ 1  2]
 [10 10]]
Matrix multiplication np.dot(v1,v2):
 [[21 22]
 [43 46]]
Matrix multiplication np.dot(v2,v1):
 [[ 7 10]
 [40 60]]
Matrix multiplication v1@v2:  short hand notation @:
 [[21 22]
 [43 46]]


## Broadcasting
"The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation"
https://docs.scipy.org/doc/numpy-1.10.0/user/basics.broadcasting.html


In [95]:
v1=np.array([1,2,3,4]).reshape(2,2)
print( "v1 +10:\n {}".format( v1+10 ) )
print( "v1 +np.array([10,20]):\n {}".format( v1+np.array([10,20]) ) )
print( "v1 +np.array([[10],[20]]):\n {}".format( v1+np.array([[10],[20]]) ) )

v1 +10:
 [[11 12]
 [13 14]]
v1 +np.array([10,20]):
 [[11 22]
 [13 24]]
v1 +np.array([[10],[20]]):
 [[11 12]
 [23 24]]


In [96]:
v1 = np.arange(4).reshape(4,1)
v2 = np.ones(5)
v3 = np.ones((4,7))
v4 = np.ones((7,4))
print( "v1:\n {}".format( v1 ) )
print( "v2:\n {}".format( v2 ) )
print( "v1+v2:\n {}".format( v1+v2 ) )
print( "v1+v2:\n {}".format( v2+v1 ) )
print( "v1+v3:\n {}".format( v1+v3 ) )
try:
    print( "v1+v4:\n {}".format( v1+v4 ) )
except Exception as e:
    print('----------- uncompatible broadcasting -------------')
    print( "v1 :\n {}".format(v1) )
    print( " v4:\n {}".format(v4) )
    print( "Try to do v1+v4:\n " )
    print('Error: '+ str(e))


v1:
 [[0]
 [1]
 [2]
 [3]]
v2:
 [1. 1. 1. 1. 1.]
v1+v2:
 [[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
v1+v2:
 [[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
v1+v3:
 [[1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4. 4.]]
----------- uncompatible broadcasting -------------
v1 :
 [[0]
 [1]
 [2]
 [3]]
 v4:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Try to do v1+v4:
 
Error: operands could not be broadcast together with shapes (4,1) (7,4) 


## Basic exploratory operations

In [97]:
x=np.array([1,1,2,2,3,3,4,4])
print( "x:\n {}".format( x ) )
print( "np.min(x): {}".format(np.min(x) ) )
print( "np.max(x): {}".format(np.max(x)  ) )
print( "Unique elements: np.unique(x):\n {}".format( np.unique(x)  ) )
print( "np.mean(x): {}".format( np.mean(x) ) )
print( "np.std(x): {}".format( np.std(x) ) )

x:
 [1 1 2 2 3 3 4 4]
np.min(x): 1
np.max(x): 4
Unique elements: np.unique(x):
 [1 2 3 4]
np.mean(x): 2.5
np.std(x): 1.118033988749895


In [98]:
#Combine basic operatins to obtains desired operations
x=np.array([1,1,2,2,3,3,4,4])
def range(x):
    return np.max(x)-np.min(x)
def norm2(x):
    return np.sum(x*x)
print( "range(x): {}".format(range(x)  ) )
print( "norm2(x): {}".format(norm2(x)  ) )


range(x): 3
norm2(x): 60


### Functions might be different from different libraries

In [99]:
x=np.ones((3,3))*[1,10,100]
print( "x:\n {}".format(x  ) )
print( "Sum from base Python package: sum(x): \n{}".format( sum(x) ) )
print( "Sum from Numpy:  np.sum(x): \n{}".format( np.sum(x) ) )

x:
 [[  1.  10. 100.]
 [  1.  10. 100.]
 [  1.  10. 100.]]
Sum from base Python package: sum(x): 
[  3.  30. 300.]
Sum from Numpy:  np.sum(x): 
333.0


## Sorting
There are 3 functions:
np.sort(): sorts and gives you the sorted output
np.argsort(): sorts and gives the indices that sorts that array. It is useful when you want to rearrange several array based on order obtained from another array
np.ndarray.sort(x) : sorts the array in place (no output)

In [100]:
x=np.array([10,1,20,2,30,3,40,4])
xs=np.sort(x)
print( "x:\n {}".format(  x) )
print( "xs:\n {}".format(  xs) )

x=np.array([10,1,20,2,30,3,40,4])
np.ndarray.sort(x)
print( "x:\n {}".format(  x) )


x=np.array([10,1,20,2,30,3,40,4])
y=np.linspace(0,7,8)
ind = np.argsort(x)
print( "ind:\n {}".format(  ind))
print( "x sorted:\n {}".format(  x[ind] ))
print( "y rearranged based on the order in x:\n {}".format(  y[ind]))           


x:
 [10  1 20  2 30  3 40  4]
xs:
 [ 1  2  3  4 10 20 30 40]
x:
 [ 1  2  3  4 10 20 30 40]
ind:
 [1 3 5 7 0 2 4 6]
x sorted:
 [ 1  2  3  4 10 20 30 40]
y rearranged based on the order in x:
 [1. 3. 5. 7. 0. 2. 4. 6.]


## Indexing and slicing
 "slicing extends Python’s basic concept of slicing to N dimensions. Basic slicing occurs when obj is a slice object (constructed by start:stop:step notation inside of brackets), an integer, or a tuple of slice objects and integers. Ellipsis and newaxis objects can be interspersed with these as well."
 https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html
 

In [126]:
x=np.arange(0,10,1)
print( "x: {}".format( x ) )
print( "x[0::2]:\n {}".format(x[0::2]) )
print( "Adding a new dimension (axis to array) {}".format( x[np.newaxis,] ) )

x: [0 1 2 3 4 5 6 7 8 9]
x[0::2]:
 [0 2 4 6 8]
Adding a new dimension (axis to array) [[0 1 2 3 4 5 6 7 8 9]]


In [160]:
x=np.ones((3,3,3,3))
# x is a mulidimensional array
x[...,0]=x[...,0]*10
x[...,1]=x[...,1]*20
x[...,2]=x[...,2]*30
#"If the number of objects in the selection tuple is less than N , then : is assumed for any subsequent dimensions.""
print( "x[:,0] is the same as x[:,0,:,:]. Are any elements different: {}".format(   np.any(x[:,0]!=x[:,0,:,:]) ) )
#To access the last dimension either we need to type all the ":" till the desired dimension or use elipsis
print( "x[...,0]:\n {}".format( x[...,0] ) )
print( "x[:,:,:,0]:\n {}".format( x[...,0] ) )

x[:,0] is the same as x[:,0,:,:]. Are any elements different: False
x[...,0]:
 [[[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]]
x[:,:,:,0]:
 [[[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]]


"Note
NumPy slicing creates a view instead of a copy as in the case of builtin Python sequences such as string, tuple and list. Care must be taken when extracting a small portion from a large array which becomes useless after the extraction, because the small portion extracted contains a reference to the large original array whose memory will not be released until all arrays derived from it are garbage-collected. In such cases an explicit copy() is recommended."